# Generated by Django 4.2.6 on 2023-10-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2023)),
                ('image', models.ImageField(upload_to='')),
                ('mahalla', models.ManyToManyField(to='regions.mahallamodel')),
            ],
        ),
    ]
