# Generated by Django 4.2.6 on 2023-10-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_yearmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearmodel',
            name='mahalla',
        ),
        migrations.AddField(
            model_name='yearmodel',
            name='mahalla',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='regions.mahallamodel'),
            preserve_default=False,
        ),
    ]
