# Generated by Django 4.2.6 on 2023-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_remove_yearmodel_mahalla_yearmodel_mahalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahallamodel',
            name='choiceses',
            field=models.CharField(choices=[('TUPROQ TURI', 'Tuproq turi'), ('SIZOT SUVI', 'Sizot suvi'), ('YER TURI', 'Yer turi'), ('YANA NIMADIR', 'Yana nimadir')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yearmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
