# Generated by Django 4.2.6 on 2023-10-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_remove_mahallamodel_choiceses_yearmodel_tavsiya'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceses', models.CharField(choices=[('TUPROQ TURI', 'Tuproq turi'), ('SIZOT SUVI', 'Sizot suvi'), ('YER TURI', 'Yer turi'), ('YANA NIMADIR', 'Yana nimadir')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mahallamodel',
            name='choices',
            field=models.ManyToManyField(to='regions.choicemodel'),
        ),
    ]
