# Generated by Django 4.2.6 on 2023-10-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_choicemodel_mahallamodel_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemodel',
            name='choiceses',
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='choice_name',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
